const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,d=0)=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const num=(n,d=1)=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const short=w=>w?`${w.slice(0,6)}…${w.slice(-4)}`:'n/a';
const dt=x=>{const d=new Date(x);return isNaN(d)?'n/a':d.toLocaleString()};
const empty=(message='No data available.')=>`<div class="empty-state"><span class="empty-icon">—</span><p>${esc(message)}</p></div>`;
const state={wallet:localStorage.poly_wallet||'',bankroll:+localStorage.poly_bankroll||100,refresh:+localStorage.poly_refresh||10,token:localStorage.poly_admin_token||'',markets:JSON.parse(localStorage.poly_market_watch||'[]'),wallets:JSON.parse(localStorage.poly_wallet_watch||'[]'),notes:JSON.parse(localStorage.poly_notes||'[]'),cache:new Map(),tf:'7d',series:'alpha',lastSync:null};
function persist(){localStorage.poly_wallet=state.wallet;localStorage.poly_bankroll=state.bankroll;localStorage.poly_refresh=state.refresh;localStorage.poly_admin_token=state.token;localStorage.poly_market_watch=JSON.stringify(state.markets);localStorage.poly_wallet_watch=JSON.stringify(state.wallets);localStorage.poly_notes=JSON.stringify(state.notes)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
async function api(path,opt={}){const ttl=opt.ttl??5000;if(!opt.method&&state.cache.has(path)){const c=state.cache.get(path);if(Date.now()-c.t<ttl)return c.v}const headers={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)headers['X-Admin-Token']=state.token;const r=await fetch(path,{...opt,headers,cache:'no-store'});const j=await r.json().catch(()=>({ok:false,error:'Invalid response'}));if(!r.ok||!j.ok)throw Error(j.error||`Request failed (${r.status})`);if(!opt.method)state.cache.set(path,{t:Date.now(),v:j});state.lastSync=new Date();updateSync();return j}
function clearCache(){state.cache.clear()}
function updateSync(){const x=$('#syncText');if(x)x.textContent=state.lastSync?`Synced ${state.lastSync.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'Connecting'}
function countdown(x){if(!x)return'Expiry unavailable';const s=(new Date(x)-Date.now())/1000;if(!isFinite(s))return'Expiry unavailable';if(s<=0)return'Expired';const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return`${d?d+'d ':''}${h}h ${m}m`}
function category(t=''){t=t.toLowerCase();if(/bitcoin|btc|ethereum|crypto|solana|xrp/.test(t))return'Crypto';if(/election|president|senate|congress|trump|democrat|republican|iran|war/.test(t))return'Politics';if(/fed|rate|inflation|gdp|econom/.test(t))return'Economy';if(/weather|rain|snow|temperature|hurricane/.test(t))return'Weather';if(/soccer|football|basketball|tennis|ufc|nba|nfl|world cup|spread|o\/u/.test(t))return'Sports';return'Other'}
function confidence(s){let v=(+s.alpha||+s.score||0)*.62+Math.min(+s.wallets||0,8)*2.6+Math.min(Math.max(+s.edge||0,0),.2)*65;if(category(s.title||s.market)==='Sports')v-=8;if((+s.wallets||0)<3)v-=10;return Math.max(0,Math.min(99,Math.round(v)))}
function kelly(fair,price){fair=+fair||0;price=+price||0;if(fair<=price||price<=0||price>=1)return{pct:0,stake:0};const full=(fair-price)/(1-price),pct=Math.min(.025,Math.max(0,full*.2));return{pct,stake:state.bankroll*pct}}
function layout(active,title,subtitle,body){const nav=[['/terminal','Terminal','Live'],['/signals','Signals','Edge'],['/arbitrage','Arbitrage','Arb'],['/wallets','Wallets','Rank'],['/flow','Flow','Live'],['/watchlist','Watchlist','Saved'],['/portfolio','Portfolio','Wallet'],['/compare','Compare','Sync'],['/analytics','Analytics','Chart'],['/notes','Notes','Journal'],['/docs','Docs','Guide'],['/settings','Settings','']];document.body.className='appbody';$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="/" data-link><span class="brandmark">Pα</span><span class="brand-copy"><b>PolyAlpha</b><small>Prediction intelligence</small></span></a><div class="navgroup"><div class="navlabel">Workspace</div><nav class="nav">${nav.map(([p,n,b])=>`<a href="${p}" data-link class="${active===p?'active':''}"><span>${n}</span><span>${b}</span></a>`).join('')}</nav></div><div class="sidefoot"><button class="btn blue" id="scanBtn" style="width:100%">Run discovery scan</button><div class="statusline"><i class="dot" id="apiDot"></i><span id="syncText">Connecting</span></div></div></aside><main class="workspace"><header class="topbar"><div class="crumb"><button class="iconbtn" id="menuBtn">☰</button><h1>${esc(title)}</h1><span>${esc(subtitle)}</span></div><div class="toptools"><div class="syncpill"><i class="dot" style="background:var(--green)"></i><span id="freshText">Live cache</span></div><div class="syncpill"><span class="label">Background sync</span><select id="refreshRate"><option value="0">Off</option><option value="5">5 sec</option><option value="10">10 sec</option><option value="30">30 sec</option></select></div><div class="clockpill"><span id="dateTop"></span><b id="clockTop">--:--:--</b></div></div></header><section class="content">${body}</section></main><nav class="mobilebar"><a href="/terminal" data-link>Terminal</a><a href="/signals" data-link>Signals</a><a href="/arbitrage" data-link>Arb</a><a href="/portfolio" data-link>Portfolio</a></nav></div>`;bindShell()}
function bindShell(){const rr=$('#refreshRate');if(rr){rr.value=String(state.refresh);rr.onchange=e=>{state.refresh=+e.target.value;persist();schedule()}}const mb=$('#menuBtn');if(mb)mb.onclick=()=>$('.sidebar').classList.toggle('open');const sb=$('#scanBtn');if(sb)sb.onclick=()=>runScan();clockTick();updateSync()}
function loading(active,title,sub){layout(active,title,sub,'<div class="loader"><div><div class="spinner"></div><p>Loading market intelligence…</p></div></div>')}
function pageHead(title,sub,actions=''){return`<div class="pagehead"><div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div>${actions}</div>`}
function landing(){document.body.className='';$('#app').innerHTML=`<div class="landing"><nav class="landing-nav"><a href="/" class="brand"><span class="brandmark">Pα</span>PolyAlpha</a><div class="landing-links"><a href="#platform">Platform</a><a href="/docs" data-link>Docs</a><a href="/arbitrage" data-link>Arbitrage</a><a href="/signals" data-link>Signals</a></div><div class="landing-actions"><a class="btn" href="/docs" data-link>Documentation</a><a class="btn primary" href="/terminal" data-link>Open terminal</a></div></nav><section class="hero"><h1>Read the market.<br><span>Follow proven skill.</span></h1><p>A professional Polymarket intelligence terminal for wallet quality, consensus signals, market flow, portfolio analytics and risk sizing.</p><div class="hero-actions"><a class="btn primary" href="/terminal" data-link>Launch terminal</a><a class="btn" href="/docs" data-link>Explore documentation</a></div><div class="product-preview" id="platform"><div class="preview-tabs"><span class="active">MARKETS</span><span>SIGNALS</span><span>WALLETS</span><span>ARBITRAGE</span><span>PORTFOLIO</span></div><div class="preview-grid"><div class="preview-card"><h3>Decision engine</h3><div class="market-line"><b>Smart-wallet consensus</b><em>Live</em></div><div class="market-line"><b>Quality-adjusted rankings</b><em>Active</em></div><div class="market-line"><b>Conservative Kelly sizing</b><em>2.5% cap</em></div><div class="market-line"><b>Market expiry tracking</b><em>Real time</em></div></div><div class="preview-card"><h3>Live intelligence</h3><div class="market-line"><b>Consensus opportunities</b><em>Positive edge</em></div><div class="market-line"><b>Wallet movement</b><em>Fresh flow</em></div><div class="market-line"><b>Cross-outcome arbitrage</b><em>Scanner</em></div><div class="market-line"><b>Portfolio diagnostics</b><em>On chain</em></div></div></div></div></section><section class="landing-features"><div class="feature"><b>Rank repeatable skill</b><p>Wallet scores reward consistency, sample size and category expertise instead of one oversized win.</p></div><div class="feature"><b>Validate consensus</b><p>Signals combine quality-adjusted wallet overlap, value, freshness, liquidity and market pricing.</p></div><div class="feature"><b>Control risk</b><p>Use conservative Kelly sizing, expiry context, watchlists and research notes before making a decision.</p></div></section><footer class="landing-footer">PolyAlpha is an analytics product, not financial advice.</footer></div>`}
async function terminal(){loading('/terminal','Terminal','Decision dashboard');const d=await api('/api/terminal');const picks=d.top_picks||[],wallets=d.top_wallets||[],whales=d.whales||[];layout('/terminal','Terminal','Decision dashboard',`${pageHead('Market intelligence','Live, quality-adjusted Polymarket discovery.','<button class="btn" id="refreshNow">Refresh data</button>')}<div class="statgrid"><div class="stat"><div class="metric">${d.smart_wallets||0}</div><div class="metric-sub">quality-scored wallets</div></div><div class="stat"><div class="metric green">${picks.length}</div><div class="metric-sub">trade-quality signals</div></div><div class="stat"><div class="metric amber">${whales.length}</div><div class="metric-sub">fresh flow events</div></div><div class="stat"><div class="metric">${state.markets.length}</div><div class="metric-sub">saved markets</div></div></div><div class="grid" style="margin-top:12px"><article class="card span8"><h3>Top opportunities</h3>${picks.length?picks.slice(0,5).map((s,i)=>signalTableRow(s,i+1)).join(''):empty('No qualified signals. The engine is correctly waiting rather than forcing a weak trade.')}</article><article class="card span4"><h3>Fresh wallet flow</h3><div class="livefeed">${whales.slice(0,7).map(flowItem).join('')||empty('No new flow events.')}</div></article><article class="card span6"><h3>Top repeatable wallets</h3>${wallets.slice(0,6).map((w,i)=>walletCompact(w,i+1)).join('')}</article><article class="card span6"><h3>Research shortcuts</h3><div class="quickgrid"><a class="quick" href="/signals" data-link><b>Review signals</b><span>Filter by category, confidence and edge.</span></a><a class="quick" href="/arbitrage" data-link><b>Scan arbitrage</b><span>Check paired sports outcomes for locked spreads.</span></a><a class="quick" href="/portfolio" data-link><b>Analyze wallet</b><span>Inspect exposure, PnL and concentration.</span></a><a class="quick" href="/notes" data-link><b>Open trade journal</b><span>Store private thesis and exit plans.</span></a></div></article></div>`);$('#refreshNow').onclick=()=>{clearCache();terminal()}}
function signalTableRow(s,i){const t=s.title||s.market||'Untitled market',c=confidence(s),k=kelly(s.fair_value,s.avg_price),slug=s.market||s.slug||'',saved=state.markets.some(x=>x.slug===slug);return`<div class="feeditem"><div><b>${i}. ${esc(t)}</b><div class="muted" style="margin-top:5px">${esc(s.outcome||'')} · ${s.wallets||0} wallets · ${category(t)} · closes ${countdown(s.closes_at)}</div><div style="margin-top:7px">Price ${num(s.avg_price,3)} → fair ${num(s.fair_value,3)} · <span class="green">edge +${num(s.edge,3)}</span></div><div class="actions" style="margin-top:9px"><button class="linkbtn market" data-slug="${esc(slug)}" data-title="${esc(t)}">Open market</button><button class="linkbtn save-market" data-slug="${esc(slug)}" data-title="${esc(t)}">${saved?'Saved':'Save'}</button></div></div><div style="text-align:right"><div class="score green">${c}%</div><small class="muted">${k.pct?money(k.stake,2):'No bet'}</small></div></div>`}
function walletCompact(w,i){const a=w.wallet||'';return`<div class="feeditem"><div><b>${i}. ${esc(w.username||short(a))}</b><small style="display:block">ROI ${num(w.roi,1)}% · ${w.trades||0} trades</small></div><div style="text-align:right"><b>${num(w.score,0)}</b><br><button class="linkbtn analyze" data-wallet="${esc(a)}">Analyze</button></div></div>`}
function flowItem(x){return`<div class="feeditem"><div><b>${esc(x.outcome||'Position')}</b><small style="display:block">${esc(x.market||'')} · ${short(x.wallet||'')}</small></div><b>${money(x.value)}</b></div>`}
async function signals(){loading('/signals','Signals','Positive-edge candidates');const d=await api('/api/picks');const picks=d.picks||[];layout('/signals','Signals','Positive-edge candidates',`${pageHead('Signals','Quality-filtered candidates with conservative sizing.')}<article class="card span12"><h3>Risk sizing</h3><div class="toolbar"><span class="muted">Bankroll</span><input id="bankroll" class="field" type="number" min="1" value="${state.bankroll}"><button id="saveBank" class="btn blue">Apply bankroll</button><div class="segmented"><button data-bank="100">$100</button><button data-bank="250">$250</button><button data-bank="500">$500</button><button data-bank="1000">$1,000</button></div><span class="muted">20% Kelly, maximum 2.5% per market.</span></div></article><article class="card span12" style="margin-top:12px"><h3>Candidate filter</h3><div class="toolbar"><input id="signalSearch" class="field" placeholder="Search market"><div class="selectwrap"><select id="signalCat" class="field"><option value="">All categories</option><option>Crypto</option><option>Politics</option><option>Economy</option><option>Weather</option><option>Sports</option><option>Other</option></select></div><div class="selectwrap"><select id="signalConf" class="field"><option value="0">Any confidence</option><option value="60">60%+</option><option value="70">70%+</option><option value="80">80%+</option></select></div></div><div id="signalList" style="margin-top:10px">${picks.length?picks.map((s,i)=>signalTableRow(s,i+1)).join(''):empty('No trade-quality signal right now.')}</div></article>`);const rerender=()=>{const q=$('#signalSearch').value.toLowerCase(),cat=$('#signalCat').value,min=+$('#signalConf').value;$('#signalList').innerHTML=picks.filter(s=>(s.title||s.market||'').toLowerCase().includes(q)&&(!cat||category(s.title||s.market)===cat)&&confidence(s)>=min).map((s,i)=>signalTableRow(s,i+1)).join('')||empty('No candidates match these filters.')};$('#signalSearch').oninput=rerender;$('#signalCat').onchange=rerender;$('#signalConf').onchange=rerender;$('#saveBank').onclick=()=>{state.bankroll=Math.max(1,+$('#bankroll').value||100);persist();toast('Bankroll applied');signals()};$$('[data-bank]').forEach(b=>b.onclick=()=>{$('#bankroll').value=b.dataset.bank})}
function arbSportConfig(sport){return sport==='Soccer'?{legs:3,labels:['Home win','Draw','Away win']}:{legs:2,labels:['Outcome 1','Outcome 2']}}
function arbCalculatorMarkup(sport='Soccer'){const c=arbSportConfig(sport);return`<article class="card span12 arb-calculator"><div class="arb-head"><div><h3>Manual arbitrage calculator</h3><p class="muted">Enter decimal odds from different bookmakers. Stakes are split to target the same payout for every outcome.</p></div><div class="segmented arb-sports" id="arbMode">${['Soccer','Tennis','Basketball','UFC'].map(x=>`<button data-sport="${x}" class="${x===sport?'active':''}">${x}${x==='Soccer'?' · 3-way':' · 2-way'}</button>`).join('')}</div></div><div class="arb-input-grid"><label class="arb-field"><span>Total stake</span><div class="input-prefix"><b>$</b><input id="arbStake" type="number" min="1" step="1" value="100"></div></label>${c.labels.map((label,i)=>`<div class="arb-leg"><label class="arb-field"><span>${label}</span><input class="arb-label" data-i="${i}" value="${label}"></label><label class="arb-field"><span>Bookmaker</span><input class="arb-bookie" data-i="${i}" placeholder="Bookie ${i+1}"></label><label class="arb-field"><span>Decimal odds</span><input class="arb-odd" data-i="${i}" type="number" min="1.01" step="0.01" placeholder="e.g. ${i===0?'2.20':i===1?'3.60':'3.40'}"></label></div>`).join('')}</div><div id="arbResult" class="arb-result neutral"><div><span>Status</span><strong>Enter all odds</strong></div><div><span>Implied total</span><strong>—</strong></div><div><span>Guaranteed return</span><strong>—</strong></div><div><span>Guaranteed profit</span><strong>—</strong></div></div><div id="arbStakes" class="arb-stakes"></div></article>`}
function calculateManualArb(){const odds=$$('.arb-odd').map(x=>+x.value),stake=Math.max(0,+($('#arbStake')?.value||0));const result=$('#arbResult'),stakes=$('#arbStakes');if(!result||!stakes)return;if(!stake||odds.some(x=>!isFinite(x)||x<=1)){result.className='arb-result neutral';result.innerHTML='<div><span>Status</span><strong>Enter valid stake and odds</strong></div><div><span>Implied total</span><strong>—</strong></div><div><span>Guaranteed return</span><strong>—</strong></div><div><span>Guaranteed profit</span><strong>—</strong></div>';stakes.innerHTML='';return}const inv=odds.map(x=>1/x),sum=inv.reduce((a,b)=>a+b,0),payout=stake/sum,profit=payout-stake,roi=profit/stake*100,isArb=sum<1;result.className=`arb-result ${isArb?'positive':'negative'}`;result.innerHTML=`<div><span>Status</span><strong>${isArb?'Arbitrage found':'No arbitrage'}</strong></div><div><span>Implied total</span><strong>${num(sum*100,2)}%</strong></div><div><span>Guaranteed return</span><strong>${money(payout,2)}</strong></div><div><span>${isArb?'Guaranteed profit':'Guaranteed loss'}</span><strong>${money(profit,2)} · ${num(roi,2)}%</strong></div>`;stakes.innerHTML=odds.map((odd,i)=>{const amount=stake*(inv[i]/sum),label=$$('.arb-label')[i]?.value||`Outcome ${i+1}`,bookie=$$('.arb-bookie')[i]?.value||`Bookie ${i+1}`;return`<div class="arb-stake-row"><div><b>${esc(label)}</b><span>${esc(bookie)} · odds ${num(odd,2)}</span></div><strong>Stake ${money(amount,2)}</strong><em>Returns ${money(amount*odd,2)}</em></div>`}).join('')}
function bindManualArb(){const mode=$('#arbMode');if(mode)mode.onclick=e=>{const b=e.target.closest('button[data-sport]');if(!b)return;const sport=b.dataset.sport;const live=$('.arb-calculator');if(live){const wrap=document.createElement('div');wrap.innerHTML=arbCalculatorMarkup(sport);live.replaceWith(wrap.firstElementChild);bindManualArb()}};$$('.arb-odd,.arb-bookie,.arb-label').forEach(x=>x.oninput=calculateManualArb);const stake=$('#arbStake');if(stake)stake.oninput=calculateManualArb}
async function arbitrage(){loading('/arbitrage','Arbitrage','Manual calculator + live scanner');let rows=[];try{const d=await api('/api/arbitrage');rows=d.opportunities||[]}catch(e){console.warn('Live arbitrage scanner unavailable:',e.message)}layout('/arbitrage','Arbitrage','Manual calculator + live scanner',`${pageHead('Arbitrage workspace','Calculate 2-way and 3-way sports arbitrage, then verify live opportunities.','<button id="arbRefresh" class="btn">Refresh live scanner</button>')}${arbCalculatorMarkup('Soccer')}<article class="card span12" style="margin-top:12px"><div class="section-title"><div><h3>Live PolyAlpha scanner</h3><p class="muted">Cached market combinations detected by the backend. Manual calculation above works independently.</p></div></div><div class="toolbar"><div class="selectwrap"><select id="arbSport" class="field"><option value="">All sports</option><option>Soccer</option><option>Tennis</option><option>Basketball</option><option>UFC</option></select></div><input id="arbMin" class="field" type="number" step="0.1" value="0" placeholder="Minimum profit %"></div><div class="tablewrap" style="margin-top:12px"><table class="table"><thead><tr><th>Market</th><th>Sport</th><th>Legs</th><th>Total cost</th><th>Gross return</th><th>Profit</th><th></th></tr></thead><tbody id="arbRows">${arbRows(rows)}</tbody></table></div></article><article class="card span6" style="margin-top:12px"><h3>How it works</h3><p class="muted">For decimal odds, arbitrage exists when the sum of each outcome's implied probability is below 100%. The calculator distributes your stake so every outcome targets the same gross payout.</p></article><article class="card span6" style="margin-top:12px"><h3>Execution check</h3><p class="muted">Confirm all odds are still available, stake limits allow the calculated amounts, fees are included, and every selection settles from the exact same event and rules.</p></article>`);bindManualArb();const filter=()=>{$('#arbRows').innerHTML=arbRows(rows.filter(x=>(!$('#arbSport').value||x.sport===$('#arbSport').value)&&(+x.profit_pct||0)>=+$('#arbMin').value))};$('#arbSport').onchange=filter;$('#arbMin').oninput=filter;$('#arbRefresh').onclick=()=>{clearCache();arbitrage()}}

function arbRows(rows){return rows.length?rows.map(x=>`<tr><td><b>${esc(x.title)}</b><br><span class="muted">${esc(x.event_key||'')}</span></td><td><span class="badge blue">${esc(x.sport)}</span></td><td>${(x.legs||[]).map(l=>`${esc(l.outcome)} @ ${num(l.price,3)}`).join('<br>')}</td><td>${money(x.total_cost,3)}</td><td>$1.000</td><td><span class="arb-profit">${num(x.profit_pct,2)}%</span></td><td><button class="linkbtn market" data-slug="${esc(x.slug||'')}" data-title="${esc(x.title)}">Open</button></td></tr>`).join(''):`<tr><td colspan="7">${empty('No verified arbitrage opportunities in the current cache.')}</td></tr>`}
async function wallets(){loading('/wallets','Wallets','Quality rankings');const d=await api('/api/topwallets?limit=100'),rows=d.wallets||[];layout('/wallets','Wallets','Quality rankings',`${pageHead('Smart-wallet rankings','Consistency-adjusted scoring that reduces one-trade and volume-spike bias.')}<article class="card span12"><div class="toolbar"><input id="walletSearch" class="field" placeholder="Search wallet or username"><div class="selectwrap"><select id="walletFocus" class="field"><option value="quality">Quality</option><option value="roi">ROI</option><option value="trades">Sample size</option><option value="pnl">PnL</option></select></div></div><div class="tablewrap" style="margin-top:12px"><table class="table"><thead><tr><th>#</th><th>Wallet</th><th>Quality</th><th>ROI</th><th>PnL</th><th>Trades</th><th></th></tr></thead><tbody id="walletRows"></tbody></table></div></article>`);const render=()=>{let x=rows.filter(w=>(w.wallet+' '+(w.username||'')).toLowerCase().includes($('#walletSearch').value.toLowerCase()));const k=$('#walletFocus').value;x.sort((a,b)=>(+b[k]||+b.score||0)-(+a[k]||+a.score||0));$('#walletRows').innerHTML=x.map((w,i)=>`<tr><td>${i+1}</td><td><b>${esc(w.username||short(w.wallet))}</b><br><span class="muted mono">${esc(short(w.wallet))}</span></td><td><span class="score">${num(w.score,1)}</span></td><td>${num(w.roi,1)}%</td><td>${money(w.pnl)}</td><td>${w.trades||0}</td><td><div class="actions"><a class="linkbtn" target="_blank" href="https://polymarket.com/profile/${esc(w.wallet)}">Profile</a><button class="linkbtn analyze" data-wallet="${esc(w.wallet)}">Analyze</button><button class="linkbtn save-wallet" data-wallet="${esc(w.wallet)}">Save</button></div></td></tr>`).join('')};render();$('#walletSearch').oninput=render;$('#walletFocus').onchange=render}
async function flow(){loading('/flow','Flow','Wallet movement');const d=await api('/api/feed');const rows=d.whales||[];layout('/flow','Flow','Wallet movement',`${pageHead('Live wallet flow','Recent high-value activity with quality context.')}<article class="card span12"><div class="tablewrap"><table class="table"><thead><tr><th>Time</th><th>Wallet</th><th>Market</th><th>Outcome</th><th>Value</th><th>Score</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${dt(x.created_at)}</td><td><a target="_blank" href="https://polymarket.com/profile/${esc(x.wallet)}">${short(x.wallet)}</a></td><td><button class="linkbtn market" data-slug="${esc(x.market)}" data-title="${esc(x.market)}">${esc(x.market)}</button></td><td>${esc(x.outcome)}</td><td>${money(x.value)}</td><td>${num(x.score,0)}</td></tr>`).join(''):`<tr><td colspan="6">${empty('No recent wallet-flow events in the current cache.')}</td></tr>`}</tbody></table></div></article>`) }
async function portfolio(){
  loading('/portfolio','Portfolio','Wallet diagnostics');
  layout('/portfolio','Portfolio','Wallet diagnostics',`${pageHead('Portfolio analysis','Enter a wallet to inspect active exposure and estimated PnL.')}<article class="card span12"><div class="toolbar"><input id="walletInput" class="field mono wallet-field" value="${esc(state.wallet)}" placeholder="0x wallet address"><button id="loadWallet" class="btn blue">Analyze wallet</button></div></article><div id="portfolioData" style="margin-top:12px">${state.wallet?'<div class="inline-loader"><span class="spinner"></span>Loading wallet…</div>':empty('Enter a wallet address to begin.')}</div>`);
  const load=async()=>{
    const address=$('#walletInput').value.trim();
    if(!/^0x[a-fA-F0-9]{40}$/.test(address)){toast('Enter a valid 0x wallet address');return}
    state.wallet=address;persist();
    $('#portfolioData').innerHTML='<div class="inline-loader"><span class="spinner"></span>Loading wallet…</div>';
    try{
      const d=await api(`/api/wallet?address=${encodeURIComponent(address)}`,{ttl:15000});
      const pos=(d.positions||[]).filter(p=>p.active!==false && !p.redeemable && (+p.value||0)>.01);
      $('#portfolioData').innerHTML=`<div class="statgrid"><div class="stat"><div class="metric">${money(d.exposure)}</div><div class="metric-sub">active market value</div></div><div class="stat"><div class="metric ${(+d.pnl_est||0)>=0?'green':'red'}">${money(d.pnl_est,2)}</div><div class="metric-sub">estimated unrealized PnL</div></div><div class="stat"><div class="metric">${pos.length}</div><div class="metric-sub">active positions</div></div><div class="stat"><div class="metric">${num(d.concentration||0,1)}%</div><div class="metric-sub">largest-position concentration</div></div></div><article class="card span12" style="margin-top:12px"><h3>Positions</h3>${pos.length?pos.map((p,i)=>signalTableRow({title:p.title,market:p.market,outcome:p.outcome,avg_price:p.current_price,fair_value:p.current_price,edge:0,wallets:0,total_value:p.value,closes_at:p.closes_at},i+1)).join(''):empty('No active positions found.')}</article>`;
    }catch(e){$('#portfolioData').innerHTML=`<div class="error-inline"><b>Wallet data unavailable</b><p>${esc(e.message)}</p><button class="btn" id="walletRetry">Retry</button></div>`;$('#walletRetry').onclick=load}
  };
  $('#loadWallet').onclick=load;
  $('#walletInput').onkeydown=e=>{if(e.key==='Enter')load()};
  if(state.wallet)load();
}
async function compare(){loading('/compare','Compare','Wallet alignment');layout('/compare','Compare','Wallet alignment',`${pageHead('Compare with smart money','Measure overlap between one wallet and cached consensus.')}<article class="card span12"><div class="toolbar"><input id="compareWallet" class="field mono" style="min-width:420px" value="${esc(state.wallet)}" placeholder="0x wallet address"><button id="compareBtn" class="btn blue">Compare</button></div></article><div id="compareData" style="margin-top:12px"></div>`);$('#compareBtn').onclick=async()=>{const d=await api(`/api/compare?address=${encodeURIComponent($('#compareWallet').value.trim())}`);$('#compareData').innerHTML=`<div class="statgrid"><div class="stat"><div class="metric">${num(d.alignment||0,0)}%</div><div class="metric-sub">smart-money alignment</div></div><div class="stat"><div class="metric">${d.matches?.length||0}</div><div class="metric-sub">matching positions</div></div><div class="stat"><div class="metric">${d.missing?.length||0}</div><div class="metric-sub">missing consensus markets</div></div><div class="stat"><div class="metric">${d.conflicts?.length||0}</div><div class="metric-sub">opposing positions</div></div></div>`}}
async function watchlist(){layout('/watchlist','Watchlist','Saved research',`${pageHead('Watchlist','Markets and wallets saved in this browser.','<button class="btn" id="exportNow">Export session</button>')}<div class="grid"><article class="card span6"><h3>Markets</h3>${state.markets.map((x,i)=>`<div class="feeditem"><div><b>${esc(x.title)}</b><small style="display:block">${esc(x.slug)}</small></div><button class="linkbtn remove-market" data-i="${i}">Remove</button></div>`).join('')||empty('No saved markets.')}</article><article class="card span6"><h3>Wallets</h3>${state.wallets.map((x,i)=>`<div class="feeditem"><div><b>${esc(x.name||short(x.wallet))}</b><small style="display:block">${esc(x.wallet)}</small></div><button class="linkbtn remove-wallet" data-i="${i}">Remove</button></div>`).join('')||empty('No saved wallets.')}</article></div>`);$('#exportNow').onclick=exportSession}
async function analytics(){
  loading('/analytics','Analytics','Historical diagnostics');
  const [ts,q,b]=await Promise.all([api(`/api/timeseries?tf=${state.tf}`),api('/api/quality'),api('/api/backtest')]);
  layout('/analytics','Analytics','Historical diagnostics',`${pageHead('Intelligence analytics','Track signal quality, wallet discovery and qualified capital flow over time.')}<article class="card span12"><div class="toolbar chart-toolbar"><div class="segmented" id="seriesTabs"><button data-series="alpha" class="${state.series==='alpha'?'active':''}">Signal quality</button><button data-series="wallets" class="${state.series==='wallets'?'active':''}">Wallet discovery</button><button data-series="flow" class="${state.series==='flow'?'active':''}">Qualified flow</button></div><div class="segmented" id="tfTabs"><button data-tf="1d" class="${state.tf==='1d'?'active':''}">1D</button><button data-tf="7d" class="${state.tf==='7d'?'active':''}">7D</button><button data-tf="30d" class="${state.tf==='30d'?'active':''}">30D</button><button data-tf="all" class="${state.tf==='all'?'active':''}">ALL</button></div></div><div class="chart-meta"><b id="chartTitle">Signal quality</b><span id="chartExplain">Average quality score of cached actionable signals.</span></div><div class="chartbox"><svg id="chart" viewBox="0 0 1000 330" preserveAspectRatio="none"></svg><div id="tip" class="tooltip hidden"></div></div></article><article class="card span6" style="margin-top:12px"><h3>Data quality</h3><p>Wallet scores: <b>${q.wallet_scores||q.scored_wallets||0}</b></p><p>Actionable positive-edge signals: <b>${q.actionable||q.actionable_signals||0}</b></p><p>Average signal wallets: <b>${num(q.avg_signal_wallets||0,1)}</b></p></article><article class="card span6" style="margin-top:12px"><h3>Backtest buckets</h3>${(b.buckets||[]).slice(0,6).map(x=>`<div class="feeditem"><span>${esc(x.bucket||x.label||'Bucket')}</span><b>${num(x.win_rate||x.hit_rate||0,1)}%</b></div>`).join('')||empty('No completed signal history yet.')}</article>`);
  drawChart(ts);
  $$('[data-series]').forEach(x=>x.onclick=()=>{state.series=x.dataset.series;$$('[data-series]').forEach(y=>y.classList.toggle('active',y===x));drawChart(ts)});
  $$('[data-tf]').forEach(x=>x.onclick=async()=>{state.tf=x.dataset.tf;clearCache();await analytics()});
}
function normalizeSeries(d,kind){
  const points=Array.isArray(d.points)?d.points:[];
  const signals=Array.isArray(d.signals)?d.signals:[];
  const flow=Array.isArray(d.flow)?d.flow:[];
  if(kind==='wallets') return (points.length?points:signals).map(x=>({t:x.t||x.ts||x.created_at,y:+(x.wallets??x.wallet_count??x.discovered??0)}));
  if(kind==='flow') return (flow.length?flow:points).map(x=>({t:x.t||x.ts||x.created_at,y:+(x.value??x.flow_value??x.whale_value??0)}));
  return (signals.length?signals:points).map(x=>({t:x.t||x.ts||x.created_at,y:+(x.score??x.alpha??x.avg_alpha??0)}));
}
function drawChart(d){
  const svg=$('#chart');if(!svg)return;
  let raw=normalizeSeries(d,state.series).filter(x=>x.t&&Number.isFinite(x.y)).sort((a,b)=>new Date(a.t)-new Date(b.t));
  const meta={alpha:['Signal quality','Average quality score (0–100) of actionable signals.'],wallets:['Wallet discovery','Quality-scored wallets discovered at each scan.'],flow:['Qualified flow','Dollar value of high-quality wallet activity.']};
  $('#chartTitle').textContent=meta[state.series][0];$('#chartExplain').textContent=meta[state.series][1];
  if(raw.length<2){svg.innerHTML='<text x="500" y="170" text-anchor="middle" class="axis">Not enough historical observations yet</text>';return}
  const W=1000,H=330,pL=58,pR=22,pT=22,pB=38,x0=+new Date(raw[0].t),x1=+new Date(raw.at(-1).t),vals=raw.map(x=>x.y),min=Math.min(...vals),max=Math.max(...vals),pad=Math.max((max-min)*.12, state.series==='alpha'?2:1),y0=Math.max(0,min-pad),y1=max+pad;
  const X=t=>pL+(+new Date(t)-x0)/Math.max(1,x1-x0)*(W-pL-pR),Y=y=>pT+(y1-y)/Math.max(1,y1-y0)*(H-pT-pB);
  let grid='';for(let i=0;i<5;i++){const y=pT+i*(H-pT-pB)/4,v=y1-(y1-y0)*i/4;grid+=`<line class="gridline" x1="${pL}" y1="${y}" x2="${W-pR}" y2="${y}"/><text class="axis" x="4" y="${y+4}">${state.series==='flow'?money(v,0):num(v,state.series==='alpha'?1:0)}</text>`}
  const path=raw.map((q,i)=>`${i?'L':'M'}${X(q.t)},${Y(q.y)}`).join(' ');
  svg.innerHTML=`<defs><linearGradient id="lineGrad"><stop stop-color="#4f8cff"/><stop offset="1" stop-color="#37d5d0"/></linearGradient><linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#4f8cff" stop-opacity=".20"/><stop offset="1" stop-color="#37d5d0" stop-opacity="0"/></linearGradient></defs>${grid}<path class="chartarea" d="${path} L${X(raw.at(-1).t)},${H-pB} L${X(raw[0].t)},${H-pB}Z"/><path class="chartline" d="${path}"/>${raw.map((q,i)=>`<circle class="dotchart" data-i="${i}" cx="${X(q.t)}" cy="${Y(q.y)}" r="4"/>`).join('')}`;
  svg.querySelectorAll('.dotchart').forEach(c=>{c.onmouseenter=e=>{const q=raw[+c.dataset.i],tip=$('#tip'),value=state.series==='flow'?money(q.y,0):num(q.y,state.series==='alpha'?1:0);tip.innerHTML=`<b>${value}</b><br>${dt(q.t)}`;tip.style.left=`${Math.min(e.offsetX+10,850)}px`;tip.style.top=`${Math.max(8,e.offsetY-20)}px`;tip.classList.remove('hidden')};c.onmouseleave=()=>$('#tip').classList.add('hidden')});
}
function notes(){layout('/notes','Notes','Trade journal',`${pageHead('Trade journal','Private notes stored locally and included in exports.')}<div class="grid"><article class="card span5"><h3>New note</h3><input id="noteMarket" class="field" style="width:100%" placeholder="Market or slug"><textarea id="noteText" class="field" style="width:100%;height:180px;margin-top:9px;padding-top:10px" placeholder="Thesis, catalysts, invalidation and exit plan"></textarea><button id="saveNote" class="btn blue" style="margin-top:9px">Save note</button></article><article class="card span7"><h3>Journal</h3>${state.notes.map((n,i)=>`<div class="feeditem"><div><b>${esc(n.market||'General note')}</b><small style="display:block">${dt(n.created)}</small><p>${esc(n.text)}</p></div><button class="linkbtn delete-note" data-i="${i}">Delete</button></div>`).join('')||empty('No notes yet.')}</article></div>`);$('#saveNote').onclick=()=>{const text=$('#noteText').value.trim();if(!text)return;state.notes.unshift({market:$('#noteMarket').value.trim(),text,created:new Date().toISOString()});persist();notes()}}
function docs(){layout('/docs','Documentation','Product guide',`${pageHead('Documentation','How PolyAlpha scores wallets, builds signals and manages risk.')}<div class="docs"><aside class="card docsnav"><a href="#start">Getting started</a><a href="#wallets">Wallet scoring</a><a href="#signals">Signal methodology</a><a href="#kelly">Bet sizing</a><a href="#arb">Arbitrage</a><a href="#security">Security</a></aside><article class="card docbody"><h3 id="start">Getting started</h3><p>Run a discovery scan, review signals, validate the market definition and liquidity, then size risk conservatively. PolyAlpha is a research terminal and never guarantees an outcome.</p><h3 id="wallets">Wallet scoring</h3><p>Wallet rankings combine ROI, realized performance, trade count, consistency, drawdown and recent activity. Small samples and one-off oversized wins receive penalties.</p><h3 id="signals">Signal methodology</h3><p>Consensus is quality weighted. A signal becomes stronger when several credible wallets agree, the position is fresh, the market is liquid and estimated fair value remains above executable price.</p><h3 id="kelly">Conservative Kelly sizing</h3><p>The website uses 20% of full Kelly and caps a single position at 2.5% of bankroll. This reduces volatility and model-error risk.</p><div class="code">stake = bankroll × min(2.5%, 20% × full Kelly)</div><h3 id="arb">Arbitrage</h3><p>The arbitrage scanner looks for paired outcomes whose combined executable cost is below $1.00. Always verify order-book depth, fees, settlement equivalence and fill risk.</p><h3 id="security">Security</h3><p>Administrative actions are rate limited and protected by WEB_ADMIN_TOKEN. Do not expose this token publicly. Watchlists and notes remain in local browser storage unless exported.</p></article></div>`)}
async function settings(){layout('/settings','Settings','Local preferences',`${pageHead('Settings','Session portability, security and background data sync.')}<div class="grid"><article class="card span6"><h3>Background sync</h3><div class="toolbar"><div class="selectwrap"><select id="settingRefresh" class="field"><option value="0">Off</option><option value="5">Every 5 seconds</option><option value="10">Every 10 seconds</option><option value="30">Every 30 seconds</option></select></div><p class="muted">Data is refreshed silently in the cache. The page is not re-rendered or interrupted.</p></div></article><article class="card span6"><h3>Session data</h3><div class="actions"><button id="exportData" class="btn">Export JSON</button><button id="importData" class="btn">Import JSON</button></div></article><article class="card span12"><h3>Default risk model</h3><p class="muted">Default bankroll is $100. Risk sizing remains 20% Kelly with a 2.5% maximum position.</p></article></div>`);$('#settingRefresh').value=String(state.refresh);$('#settingRefresh').onchange=e=>{state.refresh=+e.target.value;persist();schedule();toast('Background sync updated')};$('#exportData').onclick=exportSession;$('#importData').onclick=()=>$('#importFile').click()}
function exportSession(){const d={version:'5.0',exported:new Date().toISOString(),wallet:state.wallet,bankroll:state.bankroll,refresh:state.refresh,token:state.token,markets:state.markets,wallets:state.wallets,notes:state.notes};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download=`polyalpha-session-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function openMarket(slug,title){const d=await api(`/api/market-link?slug=${encodeURIComponent(slug||'')}&title=${encodeURIComponent(title||'')}`,{ttl:1800000});window.open(d.url,'_blank','noopener')}
async function runScan(){toast('Discovery scan started');try{await api('/api/scan',{method:'POST',body:JSON.stringify({limit:300,focus:'quality'})});clearCache();toast('Scan complete');await softRefresh()}catch(e){if(String(e.message).includes('unauthorized')){const token=prompt('Enter the private WEB_ADMIN_TOKEN to run a scan. It is stored only in this browser.');if(token){state.token=token.trim();persist();return runScan()}}toast(e.message)}}
function notFound(){layout('', '404','Page not found','<div class="errorpage"><div><b>404</b><h2>This page does not exist</h2><p class="muted">Return to the homepage or open the terminal.</p><div class="actions" style="justify-content:center"><a class="btn primary" href="/" data-link>Home</a><a class="btn" href="/terminal" data-link>Terminal</a></div></div></div>')}
async function route(){scrollTo(0,0);try{const p=location.pathname;if(p==='/'){landing();return}if(p==='/terminal')await terminal();else if(p==='/signals')await signals();else if(p==='/arbitrage')await arbitrage();else if(p==='/wallets')await wallets();else if(p==='/flow'||p==='/feed')await flow();else if(p==='/watchlist')await watchlist();else if(p==='/portfolio')await portfolio();else if(p==='/compare')await compare();else if(p==='/analytics')await analytics();else if(p==='/notes')notes();else if(p==='/docs')docs();else if(p==='/settings')await settings();else notFound()}catch(e){console.error('Route failed',e);layout('', 'Error','Unable to load','<div class="errorpage"><div><h2>Unable to load this view</h2><p class="red">'+esc(e.message||'Unknown error')+'</p><div class="actions" style="justify-content:center"><button class="btn" id="retry">Retry</button><a class="btn" href="/" data-link>Home</a></div></div></div>');$('#retry').onclick=()=>{clearCache();route()}}}
async function softRefresh(){try{state.cache.delete('/api/terminal');state.cache.delete('/api/picks');state.cache.delete('/api/feed');await Promise.all([api('/api/terminal',{ttl:0}),api('/api/picks',{ttl:0}),api('/api/feed',{ttl:0})]);const f=$('#freshText');if(f)f.textContent='Background data updated'}catch(e){const d=$('#apiDot');if(d)d.style.background='var(--red)'}}
let timer;function schedule(){clearInterval(timer);if(state.refresh)timer=setInterval(()=>{if(document.visibilityState==='visible')softRefresh()},state.refresh*1000)}
function clockTick(){const d=new Date(),c=$('#clockTop'),x=$('#dateTop');if(c)c.textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});if(x)x.textContent=d.toLocaleDateString([], {weekday:'short',day:'2-digit',month:'short'})}
setInterval(clockTick,1000);
document.addEventListener('click',e=>{const l=e.target.closest('[data-link]');if(l){e.preventDefault();history.pushState({},'',l.getAttribute('href'));route();return}const m=e.target.closest('.market');if(m)return openMarket(m.dataset.slug,m.dataset.title);const a=e.target.closest('.analyze');if(a){state.wallet=a.dataset.wallet;persist();history.pushState({},'', '/portfolio');route();return}const sm=e.target.closest('.save-market');if(sm){const i=state.markets.findIndex(x=>x.slug===sm.dataset.slug);if(i>=0)state.markets.splice(i,1);else state.markets.unshift({slug:sm.dataset.slug,title:sm.dataset.title,savedAt:new Date().toISOString()});persist();toast(i>=0?'Market removed':'Market saved');return}const sw=e.target.closest('.save-wallet');if(sw){const i=state.wallets.findIndex(x=>x.wallet===sw.dataset.wallet);if(i>=0)state.wallets.splice(i,1);else state.wallets.unshift({wallet:sw.dataset.wallet,savedAt:new Date().toISOString()});persist();toast(i>=0?'Wallet removed':'Wallet saved');return}const rm=e.target.closest('.remove-market');if(rm){state.markets.splice(+rm.dataset.i,1);persist();watchlist()}const rw=e.target.closest('.remove-wallet');if(rw){state.wallets.splice(+rw.dataset.i,1);persist();watchlist()}const dn=e.target.closest('.delete-note');if(dn){state.notes.splice(+dn.dataset.i,1);persist();notes()}});
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());state.wallet=d.wallet||'';state.bankroll=+d.bankroll||100;state.refresh=+d.refresh||10;state.token=d.token||'';state.markets=Array.isArray(d.markets)?d.markets:[];state.wallets=Array.isArray(d.wallets)?d.wallets:[];state.notes=Array.isArray(d.notes)?d.notes:[];persist();schedule();toast('Session imported');route()}catch{toast('Invalid PolyAlpha session file')}};
window.onpopstate=route;schedule();route();
