const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=(n,d=0)=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const num=(n,d=1)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=n=>`${Number(n||0).toFixed(1)}%`;
const clean=s=>String(s??'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));
const short=w=>!w?'n/a':`${String(w).slice(0,6)}…${String(w).slice(-4)}`;
const nowLocal=()=>new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});
const dateFull=iso=>{if(!iso)return'n/a';const d=new Date(iso);return isNaN(d)?clean(iso):d.toLocaleString()};
const rel=iso=>{if(!iso)return'n/a';const d=new Date(iso);if(isNaN(d))return clean(iso);let s=(d-Date.now())/1000,a=Math.abs(s);if(a<60)return`${Math.round(s)}s`;if(a<3600)return`${Math.round(s/60)}m`;if(a<86400)return`${Math.round(s/3600)}h`;return d.toLocaleDateString()};
let state={wallet:localStorage.getItem('poly_wallet')||'',bankroll:Number(localStorage.getItem('poly_bankroll')||250),tf:localStorage.getItem('poly_tf')||'7d',cache:{}};
setInterval(()=>$('#localClock').textContent=nowLocal(),1000); $('#localClock').textContent=nowLocal();
async function api(path){const r=await fetch(path,{cache:'no-store'});let j=await r.json().catch(()=>({ok:false,error:'Bad API response'})); if(!j.ok)throw new Error(j.error||'API error'); $('#apiDot').style.background='var(--green)'; $('#apiText').textContent='live API'; return j;}
function notice(t){const n=$('#notice'); n.textContent=t; n.classList.remove('hidden'); setTimeout(()=>n.classList.add('hidden'),4500)}
function card(t,b,c=''){return`<article class="card ${c}"><h3>${t}</h3>${b}</article>`}
function empty(t){return`<div class="empty">${t}</div>`}
function head(t,s){$('#pageTitle').textContent=t; $('#pageSub').textContent=s}
function marketLink(s){return s.link || (s.market_search||s.search_link) || (s.market?`https://polymarket.com/search?query=${encodeURIComponent(s.title||s.market)}`:'#')}
function kelly(fair,price){fair=+fair||0;price=+price||0;if(!fair||!price||price>=1||fair<=price)return{f:0,d:0,label:'No bet'};let full=(fair-price)/(1-price), f=Math.max(0,Math.min(full*.25,.03));return{f,d:state.bankroll*f,label:`${(f*100).toFixed(2)}% · ${money(state.bankroll*f,2)}`}}
function stars(s){s=+s||0;if(s>=85)return'★★★★★ Elite';if(s>=75)return'★★★★ Strong';if(s>=65)return'★★★ Watch';if(s>=55)return'★★ Low';return'Ignore'}
function signalRow(s,i=0){let edge=+s.edge||0, alpha=+(s.alpha||s.score||0), k=kelly(s.fair_value,s.avg_price), slug=clean(s.market||s.slug||''), link=marketLink(s), title=clean(s.title||s.market||'Untitled market');let close=s.closes_at?` · closes ${rel(s.closes_at)} (${dateFull(s.closes_at)})`:'';let verdict=alpha>=80&&edge>=.08?'TRADE WATCH':alpha>=70&&edge>0?'WATCH':'PASS';return`<div class="row signal-row"><div><div class="title">${i?i+'. ':''}${verdict} — ${title}</div><div class="small muted">${clean(s.outcome||'')} · ${s.wallets||0} wallets · ${money(s.total_value||s.value)}${close}</div><div class="small">Price <b>${num(s.avg_price,3)}</b> → fair <b>${num(s.fair_value,3)}</b> · edge <b class="${edge>=0?'green':'red'}">${edge>=0?'+':''}${edge.toFixed(3)}</b> · Kelly <b class="green">${k.label}</b></div><div class="actions"><a class="linkbtn" target="_blank" rel="noreferrer" href="${link}">Open market</a><button class="linkbtn copy" data-copy="${slug}">Copy slug</button><button class="linkbtn" onclick="research('${slug}')">Research</button></div><div class="slug">${slug}</div></div><div class="score ${edge>=0?'green':'red'}">${num(alpha,0)}/100<br><span>${stars(alpha)}</span></div></div>`}
function walletRow(w,i=0){let wallet=clean(w.wallet||''),link=`https://polymarket.com/profile/${wallet}`;return`<div class="row"><div><div class="title">${i?i+'. ':''}${short(wallet)} ${w.username?`<span class="muted">(${clean(w.username)})</span>`:''}</div><div class="small muted">ROI ${pct(w.roi)} · PnL ${money(w.pnl)} · Vol ${money(w.volume)} · Trades ${w.trades||0}</div><div class="actions"><a class="linkbtn" target="_blank" rel="noreferrer" href="${link}">Profile</a><button class="linkbtn copy" data-copy="${wallet}">Copy</button><button class="linkbtn" onclick="loadWallet('${wallet}')">Analyze</button></div><div class="slug">${wallet}</div></div><div class="score blue">${num(w.score,1)}/100</div></div>`}
function whaleRow(x){let slug=clean(x.market||''),wallet=clean(x.wallet||''),link=x.link||`https://polymarket.com/search?query=${encodeURIComponent(slug)}`;return`<div class="row"><div><div class="title">${clean(x.outcome||'Position')} · ${slug}</div><div class="small muted">${short(wallet)} · score ${num(x.score,0)}/100 · ${clean(x.created_at||'')}</div><div class="actions"><a class="linkbtn" target="_blank" rel="noreferrer" href="${link}">Market</a><a class="linkbtn" target="_blank" rel="noreferrer" href="https://polymarket.com/profile/${wallet}">Wallet</a></div></div><div class="score gold">${money(x.value)}</div></div>`}
function positionRow(p){return`<div class="row"><div><div class="title">${clean(p.title||p.market)}</div><div class="small muted">${clean(p.outcome)} · avg ${num(p.avg_price,3)} → cur ${num(p.current_price,3)} · size ${num(p.size,2)} · closes ${rel(p.closes_at)}</div><div class="actions"><a class="linkbtn" target="_blank" rel="noreferrer" href="${p.link||'#'}">Open market</a><button class="linkbtn copy" data-copy="${clean(p.market)}">Copy slug</button></div></div><div class="score ${p.pnl_est>=0?'green':'red'}">${money(p.value)}<br><span>${money(p.pnl_est,2)}</span></div></div>`}
function walletInput(){return`<div class="walletbar"><input id="walletInput" value="${clean(state.wallet)}" placeholder="Paste 0x wallet address"><button class="primary" id="saveWalletPage">Save wallet</button></div>`}
function chartBox(){return card('Interactive intelligence chart',`<div class="chartTop"><div class="chips"><button data-series="wallets" class="chip active">Wallet scans</button><button data-series="alpha" class="chip">Alpha score</button><button data-series="flow" class="chip">Whale flow</button></div><div class="tabs"><button data-tf="1d">1D</button><button data-tf="7d">7D</button><button data-tf="30d">30D</button><button data-tf="all">ALL</button></div></div><canvas id="intelChart" height="300"></canvas><div id="chartMeta" class="small muted"></div>`, 'full chartCard')}
async function loadChart(){let d=await api('/api/timeseries?tf='+state.tf);renderCanvas(d)}
function renderCanvas(d){let c=$('#intelChart');if(!c)return;let ctx=c.getContext('2d'),r=c.getBoundingClientRect(),DPR=devicePixelRatio||1;c.width=r.width*DPR;c.height=300*DPR;ctx.scale(DPR,DPR);let W=r.width,H=300,p=38;ctx.clearRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=p+i*(H-2*p)/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(W-p,y);ctx.stroke()}let pts=(d.points||[]).map(x=>({t:new Date(x.t).getTime(),y:+(x.value||x.wallets||0),raw:x})).filter(x=>!isNaN(x.t));if(!pts.length){$('#chartMeta').textContent='No chart data yet.';return}let minX=Math.min(...pts.map(x=>x.t)),maxX=Math.max(...pts.map(x=>x.t)),maxY=Math.max(1,...pts.map(x=>x.y));let X=t=>p+(t-minX)/Math.max(1,maxX-minX)*(W-2*p),Y=y=>H-p-y/maxY*(H-2*p);let g=ctx.createLinearGradient(0,0,W,0);g.addColorStop(0,'#67e8f9');g.addColorStop(1,'#8b5cf6');ctx.strokeStyle=g;ctx.lineWidth=3;ctx.beginPath();pts.forEach((pt,i)=>{let x=X(pt.t),y=Y(pt.y);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='rgba(103,232,249,.9)';pts.forEach(pt=>{ctx.beginPath();ctx.arc(X(pt.t),Y(pt.y),4,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#f6c453';(d.flow||[]).slice(-120).forEach(f=>{let x=X(new Date(f.t).getTime()), y=H-p-Math.min(90,(+f.value||0)/4000);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()});$('#chartMeta').textContent=`${String(d.timeframe).toUpperCase()} · server ${dateFull(d.now)} · ${pts.length} points`;$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tf===state.tf));}
async function home(){head('Home','A clean command center for smart-money discovery, signals, wallet analytics and alerts.');let d=await api('/api/terminal');$('#content').innerHTML=`<section class="hero full"><div><p class="eyebrow">Prediction market intelligence</p><h2>Find what the best Polymarket wallets are doing.</h2><p>PolyAlpha tracks smart wallets, consensus, whale flow, portfolio exposure and Kelly-sized trade candidates.</p><div class="actions"><a class="primary linkbtn" href="/terminal">Open terminal</a><a class="ghost linkbtn" href="/signals">View signals</a></div></div><div class="heroStats"><b>${d.discovered_wallets||0}</b><span>tracked wallets</span><b>${(d.top_picks||[]).length}</b><span>trade-quality picks</span></div></section>`+card('Core modules','<div class="modulegrid"><a href="/signals">Signals + Kelly</a><a href="/wallets">Smart wallets</a><a href="/portfolio">Portfolio analytics</a><a href="/flow">Whale flow</a><a href="/alerts">Email alerts</a><a href="/analytics">Interactive analytics</a></div>','full')}
async function terminal(){head('Terminal','Decision board, live clock, cached low-latency intelligence.');let d=await api('/api/terminal');$('#content').innerHTML=chartBox()+card('Smart wallets',`<div class="metric">${d.discovered_wallets||0}</div><div class="submetric">discovered</div>`)+card('Trade-quality picks',`<div class="metric ${d.top_picks?.length?'green':'red'}">${d.top_picks?.length||0}</div><div class="submetric">strict positive-edge</div>`)+card('Fresh whale flow',`<div class="metric gold">${d.whales?.length||0}</div><div class="submetric">latest alerts</div>`)+card('Best candidates',(d.top_picks||[]).length?d.top_picks.map(signalRow).join(''):empty('No trade-quality signal right now.'),'wide')+card('Top wallets',(d.top_wallets||[]).slice(0,5).map(walletRow).join(''))+card('Recent whales',(d.whales||[]).slice(0,4).map(whaleRow).join('')||empty('No fresh whale flow.'),'full');await loadChart()}
async function signals(){head('Signals','Strict positive-edge opportunities with Kelly sizing and market timing.');let d=await api('/api/picks');$('#content').innerHTML=card('Controls',`<div class="controls"><input id="bankroll" value="${state.bankroll}" placeholder="Bankroll"><button class="primary" id="saveBank">Save bankroll</button><span class="muted">Kelly capped at 3% using quarter-Kelly.</span></div>`,'full')+card('Best candidates',(d.picks||[]).length?d.picks.map(signalRow).join(''):empty('No trade-quality signal right now.'),'full');$('#saveBank').onclick=()=>{state.bankroll=+$('#bankroll').value||250;localStorage.setItem('poly_bankroll',state.bankroll);notice('Bankroll saved')}}
async function wallets(){head('Wallets','Ranked smart wallets with copyable addresses and Polymarket profiles.');let d=await api('/api/topwallets?limit=25');$('#content').innerHTML=card('Top smart wallets',(d.wallets||[]).map(walletRow).join('')||empty('Run a scan first.'),'full')}
async function flow(){head('Flow','Fresh whale positions and tracked wallet changes.');let d=await api('/api/feed?limit=30');$('#content').innerHTML=card('Whale flow',(d.whales||[]).map(whaleRow).join('')||empty('No whale alerts.'),'wide')+card('Position changes',(d.changes||[]).map(x=>`<div class="row"><div><div class="title">${clean(x.event_type||'change')} · ${short(x.wallet)}</div><div class="small muted">${clean(x.market||'')} · ${clean(x.created_at||'')}</div></div><div class="score blue">${money(x.value_delta||0)}</div></div>`).join('')||empty('No changes yet.'))}
async function portfolio(){head('Portfolio','Wallet exposure, active positions only, estimated unrealized PnL and market links.');$('#content').innerHTML=card('Wallet',walletInput()+'<p class="muted">Wallet exposure = current active position value. Estimated PnL = current value minus average entry cost for open positions. Closed/lost dust positions are filtered out.</p>','full');bindWallet(); if(!state.wallet)return;let d=await api('/api/wallet?address='+encodeURIComponent(state.wallet));let exp=Object.entries(d.exposure||{}).sort((a,b)=>b[1]-a[1]);$('#content').innerHTML=card('Wallet',walletInput()+'<p class="muted">Wallet exposure = current active position value. Estimated PnL = current value minus average entry cost for open positions. Closed/lost dust positions are filtered out.</p>','full')+card('Active exposure',`<div class="metric">${money(d.total_value)}</div><div class="submetric">${d.position_count} active positions</div><div class="actions"><a class="linkbtn" target="_blank" href="${d.profile}">Open profile</a><button class="linkbtn copy" data-copy="${d.wallet}">Copy wallet</button></div>`)+card('Unrealized PnL',`<div class="metric ${d.pnl_est>=0?'green':'red'}">${money(d.pnl_est,2)}</div><div class="submetric">${num(d.pnl_pct_est,2)}% estimated</div>`)+card('Exposure map',exp.length?exp.slice(0,8).map(([k,v])=>`<div class="barrow"><span>${clean(k)}</span><b>${money(v)}</b><i style="width:${Math.min(100,v/Math.max(1,exp[0][1])*100)}%"></i></div>`).join(''):empty('No active positions found.'))+card('Largest active positions',(d.positions||[]).length?d.positions.map(positionRow).join(''):empty('No active positions found.'),'full');bindWallet()}
function bindWallet(){let b=$('#saveWalletPage'); if(b)b.onclick=()=>{state.wallet=$('#walletInput').value.trim();localStorage.setItem('poly_wallet',state.wallet);notice('Wallet saved.');portfolio()}}
async function compare(){head('Compare','Compare your wallet against current smart-money consensus.');$('#content').innerHTML=card('Wallet',walletInput(),'full');bindWallet(); if(!state.wallet)return;let d=await api('/api/compare?address='+encodeURIComponent(state.wallet));$('#content').innerHTML=card('Wallet',walletInput(),'full')+card('Alignment',`<div class="metric">${num(d.overlap_pct,1)}%</div><div class="submetric">${d.overlap_count||0} shared signals</div>`)+card('Missing high-consensus trades',(d.missing||[]).map(signalRow).join('')||empty('No missing signals.'),'wide')+card('Shared positions',(d.shared||[]).map(signalRow).join('')||empty('No shared positions.'),'wide');bindWallet()}
async function analytics(){head('Analytics','Interactive chart, signal buckets and data quality.');let q=await api('/api/quality');$('#content').innerHTML=chartBox()+card('Signal buckets',`<div class="row"><div><b>Actionable</b><div class="small muted">strict positive edge</div></div><div class="score green">${q.actionable_count}</div></div><div class="row"><div><b>Consensus</b><div class="small muted">cached signals</div></div><div class="score blue">${q.consensus_count}</div></div>`)+card('Data quality',`<div class="metric">${num(q.avg_score,1)}/100</div><div class="submetric">avg wallet score</div><p class="muted">Elite ${q.elite} · Strong ${q.strong} · Good ${q.good} · Weak ${q.weak}</p>`);await loadChart()}
async function alerts(){head('Alerts','Email rules for high-quality trade candidates.');let d=await api('/api/notifications');let s=d.settings||{};$('#content').innerHTML=card('Email alerts',`<div class="formgrid"><label>Email<input id="alertEmail" value="${clean(s.email||'')}"></label><label>Min alpha<input id="alertAlpha" value="${s.min_alpha||80}"></label><label>Min edge<input id="alertEdge" value="${s.min_edge||0.08}"></label><label class="check"><input type="checkbox" id="alertEnabled" ${s.enabled?'checked':''}> Enable email alerts</label><button class="primary" id="saveAlerts">Save alerts</button></div><p class="${d.smtp_ready?'green':'red'}">SMTP status: ${d.smtp_ready?'ready':'not configured'}</p><p class="muted">To send real emails, add SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS and SMTP_FROM in Railway Variables. Until then settings are saved but no email is sent.</p>`,'wide')+card('Recommended rule',`<div class="kv"><span>Alpha score</span><b>≥ 80</b></div><div class="kv"><span>Edge</span><b>≥ 0.08</b></div><div class="kv"><span>Smart wallets</span><b>3+</b></div><div class="kv"><span>Noise control</span><b>Only strong picks</b></div>`);$('#saveAlerts').onclick=async()=>{let url=`/api/notifications?email=${encodeURIComponent($('#alertEmail').value)}&min_alpha=${encodeURIComponent($('#alertAlpha').value)}&min_edge=${encodeURIComponent($('#alertEdge').value)}&enabled=${$('#alertEnabled').checked?1:0}`;await api(url);notice('Alert settings saved.')}}
async function quality(){return analytics()}
window.research=slug=>{location.href='/signals';notice('Research opens from Telegram for now. Slug copied.');navigator.clipboard?.writeText(slug)};
window.loadWallet=w=>{state.wallet=w;localStorage.setItem('poly_wallet',w);history.pushState({},'', '/portfolio');route()};
function active(){let p=location.pathname;$$('.nav a').forEach(a=>{let href=a.getAttribute('href');a.classList.toggle('active', href===p || (p==='/'&&href==='/') || (p==='/terminal'&&href==='/terminal'))})}
async function runScan(){notice('Scan started. This can take up to 90 seconds.');let d=await api('/api/scan?limit=100');notice(`Scan complete: ${d.result?.wallets_found||0} wallets, ${d.result?.consensus_signals||0} signals.`);route()}
async function route(){active();try{let p=location.pathname;if(p==='/terminal')return terminal();if(p==='/signals')return signals();if(p==='/wallets')return wallets();if(p==='/flow'||p==='/feed')return flow();if(p==='/portfolio')return portfolio();if(p==='/compare')return compare();if(p==='/analytics'||p==='/backtest')return analytics();if(p==='/alerts'||p==='/notifications')return alerts();if(p==='/quality')return quality();return home()}catch(e){$('#apiDot').style.background='var(--red)';$('#apiText').textContent='API error';$('#content').innerHTML=card('Error',`<p class="red">${clean(e.message)}</p>`,'full')}}
document.addEventListener('click',e=>{let c=e.target.closest('.copy');if(c){navigator.clipboard?.writeText(c.dataset.copy||'');notice('Copied.')}let tf=e.target.closest('.tabs button');if(tf){state.tf=tf.dataset.tf;localStorage.setItem('poly_tf',state.tf);loadChart()}});
$$('.nav a,.brand').forEach(a=>a.onclick=e=>{e.preventDefault();history.pushState({},'',a.href);route()});
$('#quickScan').onclick=runScan; $('#refresh').onclick=route; window.onpopstate=route; route(); setInterval(()=>{if(['/terminal','/signals','/flow','/analytics'].includes(location.pathname))route()},30000);
