const $=s=>document.querySelector(s);const fmtMoney=n=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
async function api(p){const r=await fetch(p);return await r.json()}function card(title,body,cls=''){return `<div class="card ${cls}"><h2>${title}</h2>${body}</div>`}
function signal(s,i=0){const edge=Number(s.edge||0);return `<div class="row"><div><b>${i?i+'. ':''}${s.title||s.market}</b><div class="small muted">${s.outcome||''} · Alpha ${s.alpha||Math.round(s.score||0)}/100 · ${s.wallets||0} wallets · ${fmtMoney(s.total_value)}</div><div class="slug">${s.market||''}</div></div><div><div class="${edge>=0?'green':'red'}">${edge>=0?'+':''}${edge.toFixed(3)}</div>${s.link?`<a class="link small" target="_blank" href="${s.link}">Open</a>`:''}</div></div>`}
function wallet(w,i=0){return `<div class="row"><div><b>${i?i+'. ':''}${(w.wallet||'').slice(0,8)}…${(w.wallet||'').slice(-4)}</b><div class="small muted">ROI ${fmt(w.roi)}% · PnL ${fmtMoney(w.pnl)} · Trades ${w.trades||0}</div><div class="slug">${w.wallet||''}</div></div><div class="metric" style="font-size:20px">${fmt(w.score)}/100</div></div>`}
async function terminal(){const d=await api('/api/terminal');$('#pageTitle').textContent='Terminal';let picks=d.top_picks||[], wallets=d.top_wallets||[], whales=d.whales||[];$('#content').innerHTML=card('Smart wallets',`<div class="metric">${d.discovered_wallets||0}</div><div class="muted">discovered wallets</div>`)+card('Actionable picks',`<div class="metric ${picks.length?'green':'red'}">${picks.length}</div><div class="muted">positive-edge candidates</div>`)+card('Whale activity',`<div class="metric gold">${whales.length}</div><div class="muted">latest alerts</div>`)+card('Top Picks',picks.length?picks.map(signal).join(''):'<p>No trade-quality signal right now.</p>','wide')+card('Top Wallets',wallets.slice(0,5).map(wallet).join(''),'')+card('Recent Whales',whales.slice(0,6).map(x=>`<div class="row"><div><b>${x.outcome||''}</b><div class="small muted">${x.market}</div><div class="slug">${(x.wallet||'').slice(0,10)}…</div></div><div>${fmtMoney(x.value)}</div></div>`).join(''),'full')}
async function signals(){const d=await api('/api/picks');$('#pageTitle').textContent='Signals';$('#content').innerHTML=card('Best trade candidates',(d.picks||[]).map((s,i)=>signal(s,i+1)).join('')||'<p>No clean picks now.</p>','full')}
async function wallets(){const d=await api('/api/topwallets?limit=30');$('#pageTitle').textContent='Wallets';$('#content').innerHTML=card('Top smart wallets',(d.wallets||[]).map((w,i)=>wallet(w,i+1)).join(''),'full')}
async function feed(){const d=await api('/api/feed');$('#pageTitle').textContent='Feed';$('#content').innerHTML=card('Whales',(d.whales||[]).map(x=>`<div class="row"><div><b>${x.outcome}</b><div class="small muted">${x.market}</div><div class="slug">${x.wallet}</div></div><div>${fmtMoney(x.value)}</div></div>`).join(''),'wide')+card('Position changes',(d.changes||[]).map(x=>`<div class="row"><div><b>${x.action} ${x.outcome}</b><div class="small muted">${x.title||x.market}</div></div><div class="${x.delta_value>=0?'green':'red'}">${fmtMoney(x.delta_value)}</div></div>`).join(''),'')}
async function backtest(){const d=await api('/api/backtest');$('#pageTitle').textContent='Backtest';$('#content').innerHTML=card('Signal buckets',(d.buckets||[]).map(b=>`<div class="row"><div><b>${b.bucket}</b><div class="small muted">${b.signals} signals · avg alpha ${b.avg_alpha}</div></div><div class="${b.avg_edge>=0?'green':'red'}">${b.avg_edge}</div></div>`).join(''),'full')}
async function history(){const d=await api('/api/history');$('#pageTitle').textContent='History';$('#content').innerHTML=card('Wallet position events',(d.events||[]).map(x=>`<div class="row"><div><b>${x.action} ${x.outcome}</b><div class="small muted">${x.title||x.market}</div><div class="slug">${x.wallet}</div></div><div>${fmtMoney(x.new_value)}</div></div>`).join(''),'full')}
function route(){let p=location.pathname; if(p==='/signals')return signals(); if(p==='/wallets')return wallets(); if(p==='/feed')return feed(); if(p==='/backtest')return backtest(); if(p==='/history')return history(); return terminal()}document.querySelectorAll('nav a').forEach(a=>a.onclick=e=>{e.preventDefault();historyPush(a.getAttribute('href'))});function historyPush(p){window.history.pushState({},'',p);route()}window.onpopstate=route;$('#refresh').onclick=route;route();setInterval(route,30000);
